include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_return: error
    dead_code: warning
    invalid_annotation_target: ignore
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.config.dart'

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    prefer_single_quotes: true
    avoid_print: true
    avoid_relative_lib_imports: true
    always_declare_return_types: true
    annotate_overrides: true
    avoid_empty_else: true
    prefer_is_empty: true
    unnecessary_this: true
    unawaited_futures: true
    close_sinks: true
    cancel_subscriptions: true
    always_use_package_imports: true
    sort_constructors_first: true
